# Generated by Django 4.2.2 on 2024-04-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_card_remove_subitem_category_delete_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('table_number', models.IntegerField()),
                ('note', models.TextField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
