# Generated by Django 4.2.2 on 2024-04-15 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_tableorders'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableorders',
            name='order_details',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='tableorders',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=10),
            preserve_default=False,
        ),
    ]
