# Generated by Django 4.2.2 on 2024-04-15 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_tableorders_order_details_tableorders_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tableorders',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='tableorders',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=5.3, max_digits=10),
        ),
    ]
